services:
  checkpoint:
    build: .
    container_name: checkpoint
    privileged: true
    volumes:
      - /dev:/dev
    # Maps the host SPI devices to the container
    devices:
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
      - "/dev/spidev10.0:/dev/spidev10.0"
    environment:
      - API_URL=http://192.168.68.31:8080/api
    ports:
      - "8000:8000"
    restart: always